### ISSUE TITLE
give an option to cancel the game starting

### ISSUE THREAD

**Issue by simonSkrippek** [BigETI/ElectrodZMultiplayer#13]
after the game start was requested, allow the lobby owner to cancel it. either use RequestGameStop message or create new message. should probably also work when lobbyStartsAutomatically, if that issues a countdown like manually calling gameStartRequested would do. after, disable starting automatically and rely on lobby owner to manually start the game.
please communicate if a new message is implemented.

**Comment by BigETI** [comment]
[https://github.com/BigETI/ElectrodZMultiplayer/pull/14](https://github.com/BigETI/ElectrodZMultiplayer/pull/14)
