### ISSUE TITLE
Consider Implementing further Lobby Events to Inform about Entity Changes

### ISSUE THREAD

**Issue by simonSkrippek** [BigETI/ElectrodZMultiplayer#25]
because an EntityStreamer is already implemented in the multiplayer library, it seems wasteful to have another just on the other side. this would also eliminate any discrepancies between internal and external entity states.

instead, some events could be implemented to be called during the streaming sorting process, and allow the handler to easily keep track of entity state changes. there is no need to call an event just to convey an entityDelta either, if the Entity is saved by reference on the handler side.

**event<IEntity> Lobby.OnEntityCreated**
event to be called when an entity was created, allows the handler to instantiate the entity with the full entity state right away

**event<IEntity> Lobby.OnEntityDestroyed**
event to be called when an entity was destroyed, allows the handler to destroy the entity right away

**event<float / double> Lobby.OnServerTicked**
event to be called to inform the handler that the server ticked was just processed and they should update their entities according to the entity state.

**Comment by BigETI** [comment]
`OnServerTick` will still pass entity deltas, just to inform the API user what has changed. However the API user should be able to create, update and destroy user entities and non-user entities whenever their respective events are invoked.

**Comment by BigETI** [comment]
#26
