### ISSUE TITLE
Different Server responses / messages that would be great:

### ISSUE THREAD

**Issue by simonSkrippek** [BigETI/ElectrodZMultiplayer#5]
#### OnLobbyJoinFailed
Sent when the client tried to join a lobby and could not, for whatever reason. Send reason in delegate so it can be communicated to user. 
possible reasons: lobby full, lobby does not exist, user banned from lobby, already in a lobby

#### OnLobbyCreateAndJoinFailed
Sent when the client tried to create and join a lobby and could not, for whatever reason. Send reason in delegate so it can be communicated to user. 
possible reasons: invalid settings (gamemode), already in a lobby, etc

#### SendListAvailableGameModesMessage
include nullable list of tags to make search for gamemodes easier for users

**Comment by BigETI** [comment]
Resolved by https://github.com/BigETI/ElectrodZMultiplayer/commit/0cd723194462d84b9648ac534a17902af9655925
